___ 
## Numpy
___

+ NumPy is a package for performing computations with **numerical lists**.
+ Many scientific computing libraries are built NumPy. 
    + SciPy
    + pandas
    + scikit-learn
    + python-control
### Standard Import Statement

In [1]:
import numpy as np

### NumPy Arrays

The main type in NumPy is the 'numpy array' or **ndarray** (for n-dimensional array).

Create an ndarray with `np.array()`:

In [2]:
x = np.array([1,2,3])

print(x)

[1 2 3]


A NumPy array is 
+ Multi-dimensional (arrays of arrays)
+ Homogeneous (all elements are of the same type)
+ Numerical (integers, floats, or complex)

### Why prefer NumPy over native lists?
1. Specialized functionality
2. Tuned for speed. 

| NumPy arrays | Lists |
| --- | --- |
| low level types | Objects |
| homogeneous | multiple types |
| contiguous memory | scattered |


___
## Creating Arrays 
___

## 1-D Arrays 
### `np.array(x)`

### `empty(shape)` `zeros(shape)` `ones(shape)`

### `linspace(start, stop, num)`

## 2-D Arrays

___
## Manipulating Arrays
___
### `append(x,values)`: Append `values` to the end of `x`.

In [5]:
x = np.array([1,2,3])

np.append(x,[100,200])

array([  1,   2,   3, 100, 200])

### `insert(x,ind,values)`: Insert `values` into `x` at `ind`

In [6]:
x = np.array([1,2,3,4])

np.insert(x,2,[100,200])

array([  1,   2, 100, 200,   3,   4])

### `concatenate((x1,x2,...))`: Concatenate a collection of arrays. 

In [7]:
x1 = np.array([1,2,3])
x2 = np.array([4,5,6])

np.concatenate((x1,x2))

array([1, 2, 3, 4, 5, 6])

### `unique(x)`: Find the unique elements in `x`.

In [8]:
x = np.array([1,2,1,2,4,4,4,4])
print(x)
print(np.unique(x))

[1 2 1 2 4 4 4 4]
[1 2 4]


___
## Indexing
___
### 1D `[x]` where `x` is a list of indexes or a slice

In [3]:
import numpy as np
a = np.array([4,7,9,4,9,30,6,20,54])

print(a[3:8:2])

[ 4 30 20]


## more than 1D: [x,y] (instead of lists' [x][y])


In [5]:
b = np.array([(1.5,2,3),(4,5,6)])

print(b)


b[0:1, [0,2]]

[[1.5 2.  3. ]
 [4.  5.  6. ]]


array([[1.5, 3. ]])

## Boolean Indexing

In [6]:
print(a)

print(a[a>7])

[ 4  7  9  4  9 30  6 20 54]
[ 9  9 30 20 54]


___
## Iteration
___

Just like native python iterables.

In [9]:
for x in b:
    print('x:', x)
    for y in x:
        print(y)

x: [1.5 2.  3. ]
1.5
2.0
3.0
x: [4. 5. 6.]
4.0
5.0
6.0


___
## Array Operations
___
### array + array
+ Adding two python lists involves a `for` loop, or a comprehension.
+ With NumPy you can add two arrays with `+`.
+ Similar for other arithmetic operations. 

In [10]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**b)
print(a//b)
print(a%b)


[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]
[0 0 0]
[1 2 3]


### array + scalar

In [11]:
print(a+7)

[ 8  9 10]


___
## Array Methods
___


## `dot`: Matrix product

In [13]:
A = np.array([[3,2,0], [1,-1,0], [0,5,1]])
b = np.array([2,4,1])

print("A\n", A)
print("b\n", b)
print("Ab\n", A.dot(b) ) # as method of ndarray
print("AA\n", A.dot(A) ) # as method of ndarray

A
 [[ 3  2  0]
 [ 1 -1  0]
 [ 0  5  1]]
b
 [2 4 1]
Ab
 [14 -2 21]
AA
 [[11  4  0]
 [ 2  3  0]
 [ 5  0  1]]


## `T`: Transpose

In [14]:
A.T

array([[ 3,  1,  0],
       [ 2, -1,  5],
       [ 0,  0,  1]])

## `all()` `any()`: Methods on boolean arrays

In [15]:
A = np.arange(10)
B = A>4
print(B)
print(np.all(B))
print(np.any(B))

[False False False False False  True  True  True  True  True]
False
True


## `cumsum()`: Cumulative sum

In [16]:
print(A)
print(np.cumsum(A))


[0 1 2 3 4 5 6 7 8 9]
[ 0  1  3  6 10 15 21 28 36 45]


## `diff()`: Differences between subsequent elements

In [17]:
print(len(A))
print(len(np.diff(A)))

10
9


## `ceil()` `floor()` `round()`: Rounding methods

In [18]:
B = A/3
print(B)
print(np.ceil(B))
print(np.floor(B))
print(np.round(B))

[0.         0.33333333 0.66666667 1.         1.33333333 1.66666667
 2.         2.33333333 2.66666667 3.        ]
[0. 1. 1. 1. 2. 2. 2. 3. 3. 3.]
[0. 0. 0. 1. 1. 1. 2. 2. 2. 3.]
[0. 0. 1. 1. 1. 2. 2. 2. 3. 3.]


## `max()`, `min()`, `argmax()`, `argmin()`: Largest and Smallest Elements

In [20]:
import random
random.shuffle(A)

print(A)
print(np.max(A))
print(np.min(A))
print(np.argmax(A))
print(np.argmin(A))

[2 1 9 0 7 5 3 8 4 6]
9
0
2
3


## `maximum()`, `minimum()`: Element-wise max and min between two arrays

In [21]:
A = np.array([1,2,3,4,5])
B = np.array([5,4,3,2,1])
print(A)
print(B)
print(np.maximum(A,B))
print(np.minimum(A,B))

[1 2 3 4 5]
[5 4 3 2 1]
[5 4 3 4 5]
[1 2 3 2 1]


## `median()`, `mean()`, `std()`: Descriptive statistics

In [22]:
A = np.array([0,0,0,0,1,2,3,4,5,6])
print(A)
print(np.median(A))
print(np.mean(A))
print(np.std(A))

[0 0 0 0 1 2 3 4 5 6]
1.5
2.1
2.1656407827707715


## `sum()`, `prod()`: Aggregation

In [23]:
print(np.sum(A))
print(np.prod(A))

21
0


## `sort()` `argsort()`: Sorting

In [24]:
import random

a = [0,1,2,3,4,5,6,7,8,9]
random.shuffle(a)
stra = [str(x) for x in a] 
A = np.array(a)
strA = np.array(stra)

ind = np.argsort(A)

print(A)
print(ind)

print(A[ind])
print(strA[ind])


[9 8 5 4 6 7 0 2 3 1]
[6 9 7 8 3 2 4 5 1 0]
[0 1 2 3 4 5 6 7 8 9]
['0' '1' '2' '3' '4' '5' '6' '7' '8' '9']
